version: '3'
services:
  backend:
    build: .
    image: backend
    ports:
      - "8000:8000"
    environment:
      - OKTA_DOMAIN=${OKTA_DOMAIN}
      - OKTA_CLIENT_ID=${OKTA_CLIENT_ID}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - FASTAPI_URL=${FASTAPI_URL}
